on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step 2
        id: hello2
        uses: ranjeshfaethm/h-w-docker-action@v1.2
        with:
          who-to-greet: 'Captain Marvel123'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create pull request
      uses: ranjeshfaethm/action-pull-request-data-release@v1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'database'
        destination_repo: 'ranjeshfaethm/data-release'
        destination_folder: 'service-database'
        destination_base_branch: 'master'
        destination_head_branch: 'pr-review'
        user_email: 'ranjesh.chitharanjan@faethm.ai'
        user_name: 'ranjeshfaethm'
        pull_request_reviewers: 'ranjeshfaethm'
